name: Linux

on: [pull_request, workflow_dispatch]
#on: [push, pull_request, workflow_dispatch]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Check shell compatibility for workspacing
      run: tests/workspacing.sh

    - name: Check shell compatibility for packaging
      run: tests/packaging.sh

    - name: Build a clean image for workspace
      run: |
           mkdir -p empty_dir/src
           ./ros-docker.sh -c workspace empty_dir catkin_make

    - name: Build a clean image for package
      run: |
           mkdir -p empty_dir
           ./ros-docker.sh -c package empty_dir catkin_make
